[package]
name = "db"
version = "0.0.1"
authors = ["Dastanbek Samatov <dastanbeksamatov@gmail.com>"]
description = "Package for DB connection"
edition = "2018"

[dependencies]
rocksdb = "0.15.0"
parking_lot = "0.11"
# internal deps
common-types = { path = "../types" }
