[package]
name = "db"
version = "0.0.1"
authors = ["Dastanbek Samatov <dastanbeksamatov@gmail.com>"]
description = "Package for DB connection"
edition = "2018"

[dependencies]
rocksdb = { version = "0.15.0", optional = true }
parking_lot = "0.11"
thiserror = "1.0"
# internal deps
